from novastack.core.bridge.pydantic import BaseModel, Field


class PayloadRecord(BaseModel):
    """
    Payload record for observability tracking.

    Attributes:
        system_prompt: Optional system prompt used in the generation
        input_text: Optional input text provided to the model
        prompt_variables: List of variable names used in the prompt template
        prompt_variable_values: Dictionary mapping variable names to their values
        generated_text: The text generated by the model
        input_token_count: Number of tokens in the input (must be non-negative)
        generated_token_count: Number of tokens generated (must be non-negative)
        response_time: Response time in milliseconds (must be non-negative)
    """

    system_prompt: str | None = Field(
        default=None, description="System prompt used in the generation"
    )
    input_text: str | None = Field(
        default=None, description="Input text provided to the model"
    )
    prompt_variables: list[str] | None = Field(
        default=None, description="List of variable names used in the prompt template"
    )
    prompt_variable_values: dict[str, str] | None = Field(
        default=None, description="Dictionary mapping variable names to their values"
    )
    generated_text: str = Field(
        ..., description="The text generated by the model", min_length=1
    )

    input_token_count: int = Field(
        ..., ge=0, description="Number of tokens in the input"
    )
    generated_token_count: int = Field(
        ..., ge=0, description="Number of tokens generated"
    )
    response_time: int = Field(..., ge=0, description="Response time in milliseconds")
